// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/gonetwork.proto

package TCPHandshake

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TCPPack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqNum  uint32 `protobuf:"varint,1,opt,name=SeqNum,proto3" json:"SeqNum,omitempty"`
	AckNum  uint32 `protobuf:"varint,2,opt,name=AckNum,proto3" json:"AckNum,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Status  *Flags `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *TCPPack) Reset() {
	*x = TCPPack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gonetwork_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCPPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPPack) ProtoMessage() {}

func (x *TCPPack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gonetwork_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPPack.ProtoReflect.Descriptor instead.
func (*TCPPack) Descriptor() ([]byte, []int) {
	return file_proto_gonetwork_proto_rawDescGZIP(), []int{0}
}

func (x *TCPPack) GetSeqNum() uint32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *TCPPack) GetAckNum() uint32 {
	if x != nil {
		return x.AckNum
	}
	return 0
}

func (x *TCPPack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TCPPack) GetStatus() *Flags {
	if x != nil {
		return x.Status
	}
	return nil
}

type Flags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SYN bool `protobuf:"varint,1,opt,name=SYN,proto3" json:"SYN,omitempty"`
	ACK bool `protobuf:"varint,2,opt,name=ACK,proto3" json:"ACK,omitempty"`
	FIN bool `protobuf:"varint,3,opt,name=FIN,proto3" json:"FIN,omitempty"`
}

func (x *Flags) Reset() {
	*x = Flags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gonetwork_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flags) ProtoMessage() {}

func (x *Flags) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gonetwork_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flags.ProtoReflect.Descriptor instead.
func (*Flags) Descriptor() ([]byte, []int) {
	return file_proto_gonetwork_proto_rawDescGZIP(), []int{1}
}

func (x *Flags) GetSYN() bool {
	if x != nil {
		return x.SYN
	}
	return false
}

func (x *Flags) GetACK() bool {
	if x != nil {
		return x.ACK
	}
	return false
}

func (x *Flags) GetFIN() bool {
	if x != nil {
		return x.FIN
	}
	return false
}

var File_proto_gonetwork_proto protoreflect.FileDescriptor

var file_proto_gonetwork_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x54, 0x43, 0x50, 0x48, 0x61, 0x6e, 0x64,
	0x73, 0x68, 0x61, 0x6b, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x07, 0x54, 0x43, 0x50, 0x50, 0x61, 0x63,
	0x6b, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x53, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x6b,
	0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x41, 0x63, 0x6b, 0x4e, 0x75,
	0x6d, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x43,
	0x50, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x73,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3d, 0x0a, 0x05, 0x46, 0x6c, 0x61, 0x67,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x59, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03,
	0x53, 0x59, 0x4e, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x43, 0x4b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x03, 0x41, 0x43, 0x4b, 0x12, 0x10, 0x0a, 0x03, 0x46, 0x49, 0x4e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x03, 0x46, 0x49, 0x4e, 0x32, 0x47, 0x0a, 0x09, 0x48, 0x61, 0x6e, 0x64, 0x73,
	0x68, 0x61, 0x6b, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x6e, 0x53, 0x65, 0x6e, 0x64,
	0x12, 0x15, 0x2e, 0x54, 0x43, 0x50, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x2e,
	0x54, 0x43, 0x50, 0x50, 0x61, 0x63, 0x6b, 0x1a, 0x15, 0x2e, 0x54, 0x43, 0x50, 0x48, 0x61, 0x6e,
	0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x2e, 0x54, 0x43, 0x50, 0x50, 0x61, 0x63, 0x6b, 0x22, 0x00,
	0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x6f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x54,
	0x43, 0x50, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x3b, 0x54, 0x43, 0x50, 0x48,
	0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gonetwork_proto_rawDescOnce sync.Once
	file_proto_gonetwork_proto_rawDescData = file_proto_gonetwork_proto_rawDesc
)

func file_proto_gonetwork_proto_rawDescGZIP() []byte {
	file_proto_gonetwork_proto_rawDescOnce.Do(func() {
		file_proto_gonetwork_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gonetwork_proto_rawDescData)
	})
	return file_proto_gonetwork_proto_rawDescData
}

var file_proto_gonetwork_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gonetwork_proto_goTypes = []interface{}{
	(*TCPPack)(nil), // 0: TCPHandshake.TCPPack
	(*Flags)(nil),   // 1: TCPHandshake.Flags
}
var file_proto_gonetwork_proto_depIdxs = []int32{
	1, // 0: TCPHandshake.TCPPack.Status:type_name -> TCPHandshake.Flags
	0, // 1: TCPHandshake.Handshake.ConnSend:input_type -> TCPHandshake.TCPPack
	0, // 2: TCPHandshake.Handshake.ConnSend:output_type -> TCPHandshake.TCPPack
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_gonetwork_proto_init() }
func file_proto_gonetwork_proto_init() {
	if File_proto_gonetwork_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gonetwork_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCPPack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gonetwork_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Flags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gonetwork_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gonetwork_proto_goTypes,
		DependencyIndexes: file_proto_gonetwork_proto_depIdxs,
		MessageInfos:      file_proto_gonetwork_proto_msgTypes,
	}.Build()
	File_proto_gonetwork_proto = out.File
	file_proto_gonetwork_proto_rawDesc = nil
	file_proto_gonetwork_proto_goTypes = nil
	file_proto_gonetwork_proto_depIdxs = nil
}
